#!/bin/zsh
# Copyright 2012 Arunjit Singh. All Rights Reserved.
# Author: Arunjit Singh <arunjit@me.com>

# My Configuration

#echo "sourcing prog"

export NSBIN="/Users/arunjitsingh/Developer/CollegeWork/Semester8/NS/bin"
export PATH="${PATH}:/Users/arunjitsingh/Developer/bin:${NSBIN}"

# Make and change to a dir
function mdcd {
    local dir=$1
    if [[ ! "$dir" ]]; then
        echo "$ERROR_STR need exactly one argument!$COLOR_NONE"
        return 1
    fi
    mkdir -p "$dir"
    if [[ -d "$dir" ]]; then
        cd "$dir"
    else
        echo "$ERROR_STR couldn't create the directory$COLOR_NONE"
        return 2
    fi
}

# GCC, Makefile and TextMate #
function matecc {
    local fl=$1
    local BIN=''
    if [ -f "makefile" ]; then
        if [ -d "bin" ]; then
            BIN='bin/'
        elif [ -d "~/bin" ]; then
            BIN='~/bin/'
        elif [ -d "~/Developer/bin" ]; then
            BIN='~/Developer/bin/'
        fi
        if [ ! -f ${fl}.cc ]; then
echo "
${fl}: ${fl}.cc
	\$(CC) \$(LIBS) ${fl}.cc -o ${BIN}${fl} && ${BIN}${fl}" >> makefile
        fi
    else
        echo "makefile not found"
    fi
    touch ${fl}.cc
    mate ${fl}.cc makefile
}

function gccstl {
    local fl=$1
    local ot="$(basename $fl .cc)"
    echo "gcc -lstdc++ -o $ot $fl"
    gcc -lstdc++ -o $ot $fl
}
